site_name: Tutoriais e Dicas

plugins:
  - search:
      lang: 
        - en
        - pt
theme:
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  
  icon:
    repo: fontawesome/brands/git-alt

  palette: 
    # scheme: slate
    primary: light green
    accent: cyan 


nav:
  - Home :
    - Qual o objetivo desse site ?: index.md
    - Disclaimer :  disclaimer.md
    - Referências : referencias.md
  
  - Base:
    - O que aprender ? : base/o-que-aprender.md
    - Programação : iniciantes/programacao.md
    - Algebra Linear :  base/algebra-linear.md
    - Inglês :  base/ingles.md
  
  - Iniciantes :
    - Programação : iniciantes/programacao.md
    - Instalação do OpenCV C++ :  iniciantes/opencv-cpp.md
    - Processamento de Imagens Digitais : iniciantes/processamento-imagem.md
    - Projetos Iniciantes : iniciantes/projetos-iniciantes.md
    - Aulas Comunidade : iniciantes/aulas-comunidade.md
    - Artigos : iniciantes/artigos.md
    - Apêndice : iniciantes/apendice.md
  
  - Intermediarios :
    - index : intermediario/index.md
    - Cursos:  intermediario/cursos.md
    - Livros : intermediario/livros.md
    - Computação Gráfica : intermediario/ComputacaoGrafica.md
    - Deep Learning : 
      - Videos : intermediario/DeepLearning.md
      - Cursos estrangeiros :  intermediario/cursos-deep-learning.md
      

  - Avançados :
    - Cursos : avancado/Cursos.md
    - Pipeline de Visão Computacional: avancado/Pipeline.md
    - Revisões de Artigos: avancado/artigos.md
    - Livros:  avancado/livros.md
    - Full Stack Deep Learning :  avancado/FullStackDeepLearning.md
    - Dissertações : avancado/dissertacoes.md
  
  - Pipeline: pipeline/Pipeline.md
  

  - Ferramentas :
    - Programação:
      - Python : ferramentas/Python.md
    - Processamento de Imagens Digitais:
      - OpenCV :  ferramentas/opencv.md
      - Mahotas : ferramentas/Mahotas.md
      - Gluon CV: ferramentas/gluon-cv.md
      - Point Clouds Library : ferramentas/pcl.md
    - Deep Learning:
      - Tensor Flow: ferramentas/tensorflow.md
      - Pytorch: ferramentas/Pytorch.md
      - Caffe : ferramentas/Caffe.md
      - Theano : ferramentas/Theano.md
    # - CV : ferramentas/cv.md
    -  Git :  ferramentas/git.md
    - Media Pipe : ferramentas/mediapipe.md
    - OpenMMLab : ferramentas/OpenMMLab.md

  - Datasets:
    Datasets : datasets/datasets.md

  - Artigos:
    - Congressos Importantes: papers/congressos.md

  - Blogs Referências:
    - PyImageSearch : blogs-referencias/pyimagesearch.md
    - Learn Opencv : blogs-referencias/learnopencv.md

  - Livros:
    Livros : livros/livros.md
  
  - Provas e Testes : ProvasETestes/index.md

  - Imagens Médicas : https://grupo-opencv-br.github.io/imagens-medicas/

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/opencvBrasil
      name: OpenCVismo Brasil

    - icon: fontawesome/brands/discord
      link: https://discord.gg/r2qTpPfPEu
      name: OpenCVismo Brasil


  # repo_url: https://github.com/Grupo-OpenCV-BR/imagens-medicas
  # homepage: https://grupo-opencv-br.github.io/imagens-medicas/