site_name: Tutoriais e Dicas

plugins:
  - search:
      lang: 
        - en
        - pt
theme:
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  
  icon:
    repo: fontawesome/brands/git-alt

  palette: 
    # scheme: slate
    primary: light green
    accent: cyan 


nav:
  - Home :
    - Qual o objetivo desse site ?: index.md
    - Disclaimer :  disclaimer.md
    - Referências : referencias.md
  - Eventos: 
    - OpenCVismo Day: eventos/eventos.md
  - Base:
    - O que aprender ? : 
      - O que aprender : base/o-que-aprender.md
      - Programação : iniciantes/programacao.md
      - Algebra Linear :  base/algebra-linear.md
      - Inglês :  base/ingles.md
    - Base teórica:
      - O que é uma Imagem ?:  base/imagem.md
  
  - Iniciantes :
    - Introdução : iniciantes/introducao.md
    - Programação : iniciantes/programacao.md
    - Aulas Comunidade : iniciantes/aulas-comunidade.md
    - CookBook: iniciantes/CookBook.md
    - Processamento de Imagens Digitais : iniciantes/processamento-imagem.md
    - Instalação do OpenCV C++ :  iniciantes/opencv-cpp.md
    - Projetos Iniciantes : iniciantes/projetos-iniciantes.md   
    - Artigos : iniciantes/artigos.md
    - Apêndice : iniciantes/apendice.md
  
  - Intermediarios :
    - index : intermediario/index.md
    - Cursos:  intermediario/cursos.md
    - Livros : intermediario/livros.md
    - Computação Gráfica : intermediario/ComputacaoGrafica.md
    - Sensoriamento Remoto : intermediario/sensoriamento-remoto.md
    - Deep Learning : 
      - Videos : intermediario/DeepLearning.md
      - Cursos estrangeiros :  intermediario/cursos-deep-learning.md
      

  - Avançados :
    - Introdução : avancado/introducao.md
    - Cursos : avancado/Cursos.md
    - Revisões de Artigos: avancado/artigos.md
    - Livros:  avancado/livros.md
    - Full Stack Deep Learning :  avancado/FullStackDeepLearning.md
    - Dissertações : avancado/dissertacoes.md
    - 3D : avancado/3D.md
    - Fotogrametria : avancado/fotogrametria.md
  
  - Pipeline: pipeline/Pipeline.md
  

  - Ferramentas :
    - Programação:
      - Python : ferramentas/Python.md
    - Processamento de Imagens Digitais:
      - OpenCV :  ferramentas/opencv.md
      - Mahotas : ferramentas/Mahotas.md
      - Gluon CV: ferramentas/gluon-cv.md
      - Point Clouds Library : ferramentas/pcl.md
    
    - Anotação de Datasets :
      - CVAT : ferramentas/cvat.md
      - LabelMe: ferramentas/labelme.md
      - Hitachi Automotive : ferramentas/hitachi.md
      - SUSTechPOINTS : ferramentas/SUSTechPOINTS.md
      - Roboflow :  ferramentas/roboflow.md
      - Labelbox : ferramentas/labelbox.md
    
    - Deep Learning:
      - Tensor Flow: ferramentas/tensorflow.md
      - Pytorch: ferramentas/Pytorch.md
      - Caffe : ferramentas/Caffe.md
      - Theano : ferramentas/Theano.md
    # - CV : ferramentas/cv.md
    -  Git :  ferramentas/git.md
    - Media Pipe : ferramentas/mediapipe.md
    - OpenMMLab : ferramentas/OpenMMLab.md


  - Datasets:
    Datasets : datasets/datasets.md

  - Artigos:
    - Congressos Importantes: papers/congressos.md
    - Reconhecimento Facial : papers/facial.md

  - Blogs Referências:
    - PyImageSearch : blogs-referencias/pyimagesearch.md
    - Learn Opencv : blogs-referencias/learnopencv.md
    - Scratcha Pixel : blogs-referencias/scratchapixel.md

  - Livros:
    Livros : livros/livros.md
  
  - Provas e Testes : 
    - Provas e Testes: ProvasETestes/index.md
    - ICP : ProvasETestes/icp.md

  - Imagens Médicas : https://grupo-opencv-br.github.io/imagens-medicas/

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/opencvBrasil
      name: OpenCVismo Brasil

    - icon: fontawesome/brands/discord
      link: https://discord.gg/r2qTpPfPEu
      name: OpenCVismo Brasil

    - icon : fontawesome/brands/slack
      link : https://signal.group/#CjQKIEcKvAy1OwrdoBsZkyUYl6wkG-II9VJngj2ux0JM7jTIEhBrz3u2IICUoBiex71N5DIf
      name: Opencvismo Brasil - Bunker 


  # repo_url: https://github.com/Grupo-OpenCV-BR/imagens-medicas
  # homepage: https://grupo-opencv-br.github.io/imagens-medicas/